name: check

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check:
          - melpa
        file:
          - fi.el
          - sd.el
          - bk.el
          - eu.el
        include:
          - check: ert
            file: checking/sd-test.el
    steps:
    - uses: actions/checkout@v3
    - uses: purcell/setup-emacs@master
      with:
        version: snapshot
    - uses: leotaku/elisp-check@master
      with:
        check: ${{ matrix.check }}
        file: ${{ matrix.file }}
